apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap002
data:
  mysql.conf: |
    [mysqld]
    disable-log-bin = 1
    skip-name-resolve = 1
    performance-schema = 0
    local-infile = 0
    mysqlx = 0
    bind-address = [IPs removed]
    open_files_limit = 200000
    max_allowed_packet = 256M
    sql_mode = "STRICT_TRANS_TABLES,ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
 
    max_connections = 500
    thread_cache_size = 128
    table_definition_cache = 65536
    table_open_cache = 65536

    wait_timeout = 10
    connect_timeout = 5
