apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isaac-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - list
  - update
  - get
- apiGroups:
  - apps
  - statefulSets
  - namespaces
  resources:
  - deployments
  verbs:
  - create
  - delete
  - list
  - update
  - get
